// ─────────────────────────────────────────────────────────────
// SAMPLE_DATA — 25 real resume samples, single source of truth
// Used by: TemplatesPage only
// ─────────────────────────────────────────────────────────────

const API_BASE = (process.env.REACT_APP_API_URL || 'https://resumeai-b3p4.onrender.com/api').replace(/\/$/, '');

export const SAMPLE_CATEGORIES = [
  { id: 'all',        label: 'All',        icon: '🌐' },
  { id: 'technology', label: 'Technology', icon: '💻' },
  { id: 'business',   label: 'Business',   icon: '📊' },
  { id: 'finance',    label: 'Finance',    icon: '💰' },
  { id: 'education',  label: 'Education',  icon: '🎓' },
  { id: 'freshers',   label: 'Freshers',   icon: '🌱' },
];

export const CATEGORY_COLORS = {
  technology: '#3B82F6',
  business:   '#8B5CF6',
  finance:    '#10B981',
  education:  '#F59E0B',
  freshers:   '#06B6D4',
};

export const getPdfUrl = (filename) => `${API_BASE}/samples/${filename}`;

export const SAMPLES = [
  {
    id: 1, filename: 'technology_01_arjun_mehta.pdf',
    name: 'Arjun Mehta', title: 'Senior Full Stack Developer',
    category: 'technology', level: 'Senior', ats: 98,
    resumeData: {
      title: 'Arjun Mehta — Full Stack Resume',
      template: 'modern', templateColor: '#3B82F6',
      targetRole: 'Senior Full Stack Developer',
      personal: {
        name: 'Arjun Mehta', title: 'Senior Full Stack Developer',
        email: 'arjun.mehta@gmail.com', phone: '+91 98765 43210',
        location: 'Bangalore, Karnataka',
        linkedin: 'linkedin.com/in/arjunmehta',
        github: 'github.com/arjunmehta-dev', website: '',
        summary: '8+ years building scalable web applications with React, Node.js, and AWS. Led teams of 6–10 engineers delivering SaaS platforms serving 500K+ users. Passionate about clean architecture, developer experience, and mentoring junior engineers.',
      },
      skills: {
        technical: ['JavaScript', 'TypeScript', 'Python', 'Go', 'React', 'Next.js', 'Node.js', 'GraphQL'],
        soft: ['Team Leadership', 'Mentoring', 'Agile/Scrum'],
        tools: ['AWS', 'Docker', 'Kubernetes', 'PostgreSQL', 'MongoDB', 'Redis'],
        languages: [],
      },
      experience: [
        { company: 'Razorpay', role: 'Senior Full Stack Developer', location: 'Bangalore', startDate: 'Jan 2021', endDate: '', current: true, description: 'Architected microservices system handling 2M+ daily transactions with 99.99% uptime.', bullets: ['Led migration from monolith to microservices, reducing deployment time by 70%', 'Mentored team of 8 engineers; introduced code review practices cutting bugs by 40%', 'Built real-time payment dashboard using React + WebSockets serving 50K daily active users'] },
        { company: 'Freshworks', role: 'Full Stack Developer', location: 'Chennai', startDate: 'Jun 2018', endDate: 'Dec 2020', current: false, description: 'Developed CRM features used by 10,000+ enterprise clients across 30 countries.', bullets: ['Optimized PostgreSQL queries reducing average response time from 800ms to 120ms', 'Built automated testing suite with 90%+ coverage using Jest and Cypress'] },
        { company: 'Infosys', role: 'Junior Developer', location: 'Pune', startDate: 'Jul 2016', endDate: 'May 2018', current: false, description: 'Built RESTful APIs for banking client serving 1M+ customers.', bullets: ['Implemented OAuth2 authentication reducing login-related support tickets by 60%'] },
      ],
      education: [{ institution: 'IIT Bombay', degree: 'B.Tech', field: 'Computer Science', startYear: '2012', endYear: '2016', gpa: '8.7/10', honors: '' }],
      projects: [
        { name: 'OpenMetrics', description: 'Open-source monitoring tool with 2.4K GitHub stars', technologies: ['Go', 'Prometheus', 'Grafana'], url: 'github.com/arjunmehta-dev/openmetrics', github: '' },
        { name: 'ReactForm Pro', description: 'Form library with 50K+ weekly npm downloads', technologies: ['React', 'TypeScript'], url: '', github: '' },
      ],
      certifications: [],
    },
  },
  {
    id: 2, filename: 'technology_02_priya_krishnamurthy.pdf',
    name: 'Priya Krishnamurthy', title: 'Machine Learning Engineer',
    category: 'technology', level: 'Senior', ats: 96,
    resumeData: {
      title: 'Priya Krishnamurthy — ML Engineer Resume',
      template: 'modern', templateColor: '#3B82F6',
      targetRole: 'Machine Learning Engineer',
      personal: {
        name: 'Priya Krishnamurthy', title: 'Machine Learning Engineer',
        email: 'priya.k@protonmail.com', phone: '+91 87654 32109',
        location: 'Hyderabad, Telangana',
        linkedin: 'linkedin.com/in/priyakrishna-ml',
        github: 'github.com/priyakrishna-ai', website: '',
        summary: 'ML Engineer with 5 years specializing in NLP and computer vision. Deployed production models serving 10M+ inferences/day. PhD candidate in Deep Learning. Published 3 papers in top-tier conferences.',
      },
      skills: {
        technical: ['PyTorch', 'TensorFlow', 'Hugging Face', 'scikit-learn', 'Python', 'R', 'SQL', 'Scala'],
        soft: ['Research', 'Technical Communication', 'Problem Solving'],
        tools: ['MLflow', 'Kubeflow', 'SageMaker', 'Airflow', 'Spark', 'Docker'],
        languages: [],
      },
      experience: [
        { company: 'Flipkart', role: 'Senior ML Engineer', location: 'Bangalore', startDate: 'Mar 2022', endDate: '', current: true, description: 'Built product recommendation engine improving CTR by 23% (₹180Cr annual revenue impact).', bullets: ['Deployed BERT-based search ranking model reducing irrelevant results by 35%', 'Designed MLOps pipeline cutting model deployment time from 2 weeks to 4 hours', 'Led team of 4 ML engineers on real-time fraud detection system (99.2% precision)'] },
        { company: 'Amazon', role: 'ML Engineer', location: 'Hyderabad', startDate: 'Aug 2019', endDate: 'Feb 2022', current: false, description: 'Developed NLP models for Alexa India supporting 8 regional languages.', bullets: ['Improved ASR accuracy by 18% using self-supervised learning on 10TB audio data', 'Built A/B testing framework for model evaluation used across 5 teams'] },
      ],
      education: [
        { institution: 'IIT Hyderabad', degree: 'PhD', field: 'Computer Science (AI/ML)', startYear: '2020', endYear: '2025', gpa: '', honors: 'Expected' },
        { institution: 'BITS Pilani', degree: 'M.Tech', field: 'Artificial Intelligence', startYear: '2017', endYear: '2019', gpa: '9.1/10', honors: '' },
      ],
      projects: [{ name: 'IndoNLP Toolkit', description: 'NLP library for Indian languages — 800+ GitHub stars', technologies: ['Python', 'Transformers'], url: '', github: 'github.com/priyakrishna-ai/indonlp' }],
      certifications: [],
    },
  },
  {
    id: 3, filename: 'technology_03_rahul_singhania.pdf',
    name: 'Rahul Singhania', title: 'DevOps & Cloud Architect',
    category: 'technology', level: 'Lead', ats: 95,
    resumeData: {
      title: 'Rahul Singhania — DevOps Resume',
      template: 'modern', templateColor: '#3B82F6',
      targetRole: 'Cloud Architect',
      personal: {
        name: 'Rahul Singhania', title: 'DevOps & Cloud Architect',
        email: 'rahul.singhania@outlook.com', phone: '+91 99887 76655',
        location: 'Pune, Maharashtra', linkedin: 'linkedin.com/in/rahulsinghania-devops',
        github: '', website: '',
        summary: 'Cloud Architect with 10 years designing resilient, cost-optimized infrastructure on AWS and Azure. Reduced infrastructure costs by $2M+ across clients. Certified in AWS, Azure, and GCP. Expert in SRE practices and GitOps.',
      },
      skills: {
        technical: ['AWS', 'Azure', 'GCP', 'Terraform', 'Kubernetes', 'Docker', 'Helm', 'Istio'],
        soft: ['Architecture Design', 'Team Leadership', 'Cost Optimization'],
        tools: ['Jenkins', 'GitHub Actions', 'ArgoCD', 'Prometheus', 'Grafana', 'Datadog', 'ELK Stack'],
        languages: [],
      },
      experience: [
        { company: 'Wipro Digital', role: 'Cloud Architect', location: 'Pune', startDate: 'Apr 2020', endDate: '', current: true, description: 'Designed multi-region AWS architecture for BFSI client handling ₹5000Cr daily transactions.', bullets: ['Reduced cloud spend by $1.2M/year through reserved instances and auto-scaling', 'Led Kubernetes migration for 200+ microservices with zero-downtime deployments', 'Established SRE practices achieving 99.95% SLA across 15 production systems'] },
        { company: 'Persistent Systems', role: 'Senior DevOps Engineer', location: 'Pune', startDate: 'Jan 2017', endDate: 'Mar 2020', current: false, description: 'Built GitOps pipeline reducing release cycles from monthly to daily.', bullets: ['Implemented Terraform IaC for 3 AWS accounts with 400+ resources', 'Automated disaster recovery cutting RTO from 4 hours to 15 minutes'] },
        { company: 'TCS', role: 'Systems Engineer', location: 'Mumbai', startDate: 'Jul 2014', endDate: 'Dec 2016', current: false, description: 'Managed Linux infrastructure for 500+ servers across 3 data centers.', bullets: ['Automated provisioning with Ansible reducing setup time by 80%'] },
      ],
      education: [{ institution: 'University of Pune', degree: 'B.E.', field: 'Information Technology', startYear: '2010', endYear: '2014', gpa: '7.9/10', honors: '' }],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 4, filename: 'technology_04_sneha_patel.pdf',
    name: 'Sneha Patel', title: 'Android Developer',
    category: 'technology', level: 'Mid', ats: 94,
    resumeData: {
      title: 'Sneha Patel — Android Developer Resume',
      template: 'modern', templateColor: '#3B82F6',
      targetRole: 'Senior Android Developer',
      personal: {
        name: 'Sneha Patel', title: 'Android Developer',
        email: 'sneha.patel.dev@gmail.com', phone: '+91 76543 21098',
        location: 'Ahmedabad, Gujarat', linkedin: 'linkedin.com/in/sneha-android',
        github: 'github.com/snehapatel-android', website: '',
        summary: 'Android Developer with 6 years building high-performance apps with 5M+ combined downloads. Expert in Kotlin, Jetpack Compose, and clean architecture. Published 3 apps on Play Store independently.',
      },
      skills: {
        technical: ['Kotlin', 'Java', 'Jetpack Compose', 'MVVM', 'Room DB', 'WorkManager', 'Hilt/Dagger'],
        soft: ['Clean Code', 'Mentoring', 'User-Centric Thinking'],
        tools: ['Android Studio', 'Firebase', 'Retrofit', 'Coroutines/Flow', 'JUnit', 'Espresso'],
        languages: [],
      },
      experience: [
        { company: 'PhonePe', role: 'Senior Android Developer', location: 'Bangalore', startDate: 'Feb 2021', endDate: '', current: true, description: 'Rebuilt payments screen in Jetpack Compose improving rendering speed by 40%.', bullets: ['Implemented biometric authentication for 150M+ users with 99.8% success rate', 'Reduced app crash rate from 0.8% to 0.1% through systematic crash analysis'] },
        { company: 'Paytm', role: 'Android Developer', location: 'Noida', startDate: 'Jul 2018', endDate: 'Jan 2021', current: false, description: 'Developed UPI payment flow handling 10M+ daily transactions.', bullets: ['Optimized app startup time by 55% using lazy initialization and baseline profiles'] },
      ],
      education: [{ institution: 'NIT Surat', degree: 'B.Tech', field: 'Information Technology', startYear: '2014', endYear: '2018', gpa: '8.4/10', honors: '' }],
      projects: [{ name: 'SpendWise', description: 'Personal finance app — 200K+ downloads, 4.7★ Play Store', technologies: ['Kotlin', 'Compose', 'Room'], url: '', github: '' }],
      certifications: [],
    },
  },
  {
    id: 5, filename: 'technology_05_vikram_nair.pdf',
    name: 'Vikram Nair', title: 'Cybersecurity Engineer',
    category: 'technology', level: 'Senior', ats: 93,
    resumeData: {
      title: 'Vikram Nair — Cybersecurity Resume',
      template: 'modern', templateColor: '#3B82F6',
      targetRole: 'Lead Security Engineer',
      personal: {
        name: 'Vikram Nair', title: 'Cybersecurity Engineer',
        email: 'vikram.nair.sec@gmail.com', phone: '+91 88776 65544',
        location: 'Kochi, Kerala', linkedin: 'linkedin.com/in/vikramnair-security',
        github: 'github.com/vikramnair-sec', website: '',
        summary: 'Cybersecurity professional with 7 years in penetration testing, incident response, and security architecture. Identified 200+ critical vulnerabilities for Fortune 500 clients. CISSP and CEH certified. Bug bounty hunter with $85K+ in rewards.',
      },
      skills: {
        technical: ['Penetration Testing', 'Red Teaming', 'SIEM', 'Threat Hunting', 'Incident Response', 'Zero Trust'],
        soft: ['Analytical Thinking', 'Report Writing', 'Risk Communication'],
        tools: ['Metasploit', 'Burp Suite', 'Nmap', 'Wireshark', 'Splunk', 'AWS Security Hub'],
        languages: [],
      },
      experience: [
        { company: 'Deloitte', role: 'Lead Security Engineer', location: 'Kochi / Remote', startDate: 'Sep 2020', endDate: '', current: true, description: 'Conducted 40+ penetration tests for BFSI and healthcare clients, reporting 200+ critical CVEs.', bullets: ['Led incident response for ransomware attack on NBFC client, restoring operations in 18 hours', 'Designed Zero Trust architecture reducing attack surface by 60%'] },
        { company: 'KPMG India', role: 'Security Analyst', location: 'Bangalore', startDate: 'Jun 2017', endDate: 'Aug 2020', current: false, description: 'Performed VAPT assessments for 25+ clients across banking and retail sectors.', bullets: ['Implemented SOC procedures reducing mean time to detect (MTTD) by 45%'] },
      ],
      education: [{ institution: 'College of Engineering Trivandrum', degree: 'B.Tech', field: 'Computer Science', startYear: '2013', endYear: '2017', gpa: '8.2/10', honors: '' }],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 6, filename: 'business_01_ananya_sharma.pdf',
    name: 'Ananya Sharma', title: 'Product Manager',
    category: 'business', level: 'Senior', ats: 97,
    resumeData: {
      title: 'Ananya Sharma — Product Manager Resume',
      template: 'modern', templateColor: '#8B5CF6',
      targetRole: 'Senior Product Manager',
      personal: {
        name: 'Ananya Sharma', title: 'Senior Product Manager',
        email: 'ananya.sharma.pm@gmail.com', phone: '+91 97654 32198',
        location: 'Gurgaon, Haryana', linkedin: 'linkedin.com/in/ananyasharma-pm',
        github: '', website: '',
        summary: 'Strategic Product Manager with 8 years driving 0→1 and scale products in fintech and e-commerce. Launched products generating $50M+ ARR. MBA from IIM Ahmedabad. Strong data intuition combined with deep user empathy.',
      },
      skills: {
        technical: ['Product Strategy', 'Roadmapping', 'OKR Framework', 'A/B Testing', 'SQL', 'Data Analysis'],
        soft: ['Cross-functional Leadership', 'Stakeholder Management', 'Executive Communication'],
        tools: ['JIRA', 'Confluence', 'Figma', 'Mixpanel', 'Amplitude', 'Tableau'],
        languages: [],
      },
      experience: [
        { company: 'Paytm', role: 'Senior Product Manager', location: 'Gurgaon', startDate: 'Mar 2021', endDate: '', current: true, description: 'Owned P&L for Paytm Loans — grew disbursements from ₹200Cr to ₹1800Cr in 18 months.', bullets: ['Launched credit score feature used by 8M+ users with 72 NPS score', 'Led cross-functional team of 25 across engineering, design, data, marketing, compliance'] },
        { company: 'Myntra', role: 'Product Manager', location: 'Bangalore', startDate: 'Jul 2018', endDate: 'Feb 2021', current: false, description: 'Built personalisation engine increasing session-to-purchase rate by 18%.', bullets: ['Launched size recommendation feature reducing returns by 22% (₹80Cr annual savings)'] },
      ],
      education: [
        { institution: 'IIM Ahmedabad', degree: 'MBA', field: 'Marketing & Strategy', startYear: '2014', endYear: '2016', gpa: '3.8/4.0', honors: '' },
        { institution: 'Lady Shri Ram College', degree: 'B.Com (Hons)', field: 'Commerce', startYear: '2011', endYear: '2014', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 7, filename: 'business_02_rajesh_kulkarni.pdf',
    name: 'Rajesh Kulkarni', title: 'Operations Director',
    category: 'business', level: 'Lead', ats: 95,
    resumeData: {
      title: 'Rajesh Kulkarni — Operations Director Resume',
      template: 'modern', templateColor: '#8B5CF6',
      targetRole: 'Director of Operations',
      personal: {
        name: 'Rajesh Kulkarni', title: 'Operations Director',
        email: 'rajesh.kulkarni@gmail.com', phone: '+91 96543 21987',
        location: 'Mumbai, Maharashtra', linkedin: 'linkedin.com/in/rajeshkulkarni-ops',
        github: '', website: '',
        summary: 'Operations leader with 15 years streamlining supply chain and logistics for FMCG giants. Delivered $30M+ in cost savings. Six Sigma Black Belt. Led teams of 200+ across India and Southeast Asia.',
      },
      skills: {
        technical: ['Supply Chain Management', 'Inventory Optimization', 'Demand Planning', 'S&OP', 'Six Sigma', 'Lean Manufacturing'],
        soft: ['P&L Management', 'Cross-functional Leadership', 'Vendor Management'],
        tools: ['SAP', 'Oracle SCM', 'Power BI', 'Advanced Excel', 'MS Project'],
        languages: [],
      },
      experience: [
        { company: 'Hindustan Unilever', role: 'Director – Operations', location: 'Mumbai', startDate: 'Jan 2019', endDate: '', current: true, description: 'Managed ₹2500Cr supply chain for Home Care division across 28 states.', bullets: ['Reduced logistics cost by 18% (₹45Cr savings) through network optimization', 'Achieved 98.5% on-shelf availability up from 91%'] },
        { company: 'ITC Limited', role: 'Senior Manager – Supply Chain', location: 'Kolkata', startDate: 'Aug 2014', endDate: 'Dec 2018', current: false, description: 'Managed end-to-end supply chain for Foods division (₹800Cr revenue).', bullets: ['Implemented SAP IBP reducing forecast error from 35% to 12%'] },
      ],
      education: [
        { institution: 'XLRI Jamshedpur', degree: 'MBA', field: 'Operations Management', startYear: '2007', endYear: '2009', gpa: '', honors: '' },
        { institution: 'VJTI Mumbai', degree: 'B.E.', field: 'Mechanical', startYear: '2003', endYear: '2007', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 8, filename: 'business_03_meera_iyer.pdf',
    name: 'Meera Iyer', title: 'Business Development Manager',
    category: 'business', level: 'Mid', ats: 94,
    resumeData: {
      title: 'Meera Iyer — Business Development Resume',
      template: 'modern', templateColor: '#8B5CF6',
      targetRole: 'Senior Business Development Manager',
      personal: {
        name: 'Meera Iyer', title: 'Business Development Manager',
        email: 'meera.iyer.biz@gmail.com', phone: '+91 85432 10987',
        location: 'Chennai, Tamil Nadu', linkedin: 'linkedin.com/in/meeraiyer-bd',
        github: '', website: '',
        summary: 'Business Development professional with 7 years closing enterprise deals in SaaS. Generated $25M+ in new ARR. Consistent top performer — exceeded quota 6 consecutive years. MBA from ISB.',
      },
      skills: {
        technical: ['Enterprise Sales', 'Solution Selling', 'Account Management', 'Pipeline Management', 'Contract Negotiation'],
        soft: ['Relationship Building', 'C-suite Presentations', 'Persuasion'],
        tools: ['Salesforce', 'HubSpot', 'LinkedIn Sales Navigator', 'ZoomInfo'],
        languages: [],
      },
      experience: [
        { company: 'Zoho Corporation', role: 'Business Development Manager', location: 'Chennai', startDate: 'Apr 2020', endDate: '', current: true, description: 'Grew enterprise segment from $2M to $8M ARR in 3 years in South India territory.', bullets: ['Closed 3 deals >$1M TCV each with Fortune 500 manufacturing companies', 'Maintained 118% of quota for 3 consecutive years'] },
        { company: 'Freshworks', role: 'Senior Sales Executive', location: 'Chennai', startDate: 'Jun 2017', endDate: 'Mar 2020', current: false, description: 'Managed portfolio of 80+ SMB accounts with $3.5M ARR.', bullets: ['Won Best Sales Executive award 2018 and 2019'] },
      ],
      education: [
        { institution: 'ISB Hyderabad', degree: 'MBA', field: 'Marketing & Strategy', startYear: '2015', endYear: '2017', gpa: '', honors: '' },
        { institution: 'Stella Maris College', degree: 'B.Com', field: 'Commerce', startYear: '2012', endYear: '2015', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 9, filename: 'business_04_karan_malhotra.pdf',
    name: 'Karan Malhotra', title: 'Human Resources Manager',
    category: 'business', level: 'Mid', ats: 93,
    resumeData: {
      title: 'Karan Malhotra — HR Manager Resume',
      template: 'modern', templateColor: '#8B5CF6',
      targetRole: 'HR Manager',
      personal: {
        name: 'Karan Malhotra', title: 'Human Resources Manager',
        email: 'karan.malhotra.hr@gmail.com', phone: '+91 93210 98765',
        location: 'Delhi, NCR', linkedin: 'linkedin.com/in/karanmalhotra-hr',
        github: '', website: '',
        summary: 'HR leader with 9 years building high-performing cultures in tech startups and MNCs. Scaled two companies from 50 to 500 employees. Expert in talent acquisition, HRBP, and organizational design. SHRM-CP certified.',
      },
      skills: {
        technical: ['Talent Acquisition', 'Performance Management', 'L&D', 'Comp & Benefits', 'HR Analytics'],
        soft: ['Culture Building', 'Coaching', 'Change Management', 'Conflict Resolution'],
        tools: ['Workday', 'Darwinbox', 'Keka', 'GreytHR', 'LinkedIn Recruiter'],
        languages: [],
      },
      experience: [
        { company: 'Swiggy', role: 'HR Manager', location: 'Bangalore / Delhi', startDate: 'Feb 2020', endDate: '', current: true, description: 'Scaled tech hiring from 80 to 350 engineers in 18 months during hypergrowth phase.', bullets: ['Reduced time-to-hire from 65 days to 28 days through process redesign', 'Built diversity program increasing women in tech roles from 18% to 34%'] },
        { company: 'Ola Cabs', role: 'HR Business Partner', location: 'Bangalore', startDate: 'Aug 2016', endDate: 'Jan 2020', current: false, description: 'HRBP for Product and Engineering divisions (800+ employees).', bullets: ['Led culture integration during acquisition of Foodpanda India (1200 employees)'] },
      ],
      education: [
        { institution: 'TISS Mumbai', degree: 'MBA', field: 'Human Resources', startYear: '2013', endYear: '2015', gpa: '', honors: '' },
        { institution: 'Delhi University', degree: 'B.A.', field: 'Psychology', startYear: '2010', endYear: '2013', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 10, filename: 'business_05_divya_nambiar.pdf',
    name: 'Divya Nambiar', title: 'Marketing Manager',
    category: 'business', level: 'Mid', ats: 92,
    resumeData: {
      title: 'Divya Nambiar — Marketing Manager Resume',
      template: 'modern', templateColor: '#8B5CF6',
      targetRole: 'Senior Marketing Manager',
      personal: {
        name: 'Divya Nambiar', title: 'Marketing Manager',
        email: 'divya.nambiar.mkt@gmail.com', phone: '+91 79876 54321',
        location: 'Bangalore, Karnataka', linkedin: 'linkedin.com/in/divyanambiar-marketing',
        github: '', website: '',
        summary: 'Performance-driven Marketing Manager with 6 years in digital marketing and brand building. Managed $5M+ annual media budgets. Grew organic traffic 8x at two startups. MBA from SP Jain.',
      },
      skills: {
        technical: ['SEO/SEM', 'Performance Marketing', 'Email Marketing', 'Content Strategy', 'Brand Management'],
        soft: ['Creative Direction', 'Brand Storytelling', 'Data-Driven Thinking'],
        tools: ['Google Analytics 4', 'HubSpot', 'Semrush', 'Meta Ads Manager', 'Google Ads', 'Mixpanel'],
        languages: [],
      },
      experience: [
        { company: 'CRED', role: 'Marketing Manager', location: 'Bangalore', startDate: 'Jun 2021', endDate: '', current: true, description: 'Managed ₹40Cr annual performance marketing budget with 3.2x ROAS.', bullets: ['Grew SEO organic traffic from 200K to 1.6M monthly visitors in 18 months', 'Launched referral program acquiring 500K users at 60% lower CAC than paid channels'] },
        { company: 'Urban Company', role: 'Digital Marketing Lead', location: 'Gurgaon', startDate: 'Jan 2019', endDate: 'May 2021', current: false, description: 'Owned demand generation across 18 cities — grew GMV from ₹50Cr to ₹200Cr.', bullets: ['Ran 200+ A/B tests on landing pages improving CVR by 45%'] },
      ],
      education: [
        { institution: 'SP Jain Institute of Management', degree: 'MBA', field: 'Marketing', startYear: '2017', endYear: '2019', gpa: '', honors: '' },
        { institution: 'Symbiosis Pune', degree: 'B.Sc', field: 'Mass Communication', startYear: '2014', endYear: '2017', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 11, filename: 'finance_01_aditya_gupta.pdf',
    name: 'Aditya Gupta', title: 'CA & Finance Manager',
    category: 'finance', level: 'Senior', ats: 96,
    resumeData: {
      title: 'Aditya Gupta — CA Finance Resume',
      template: 'modern', templateColor: '#10B981',
      targetRole: 'Finance Manager',
      personal: {
        name: 'Aditya Gupta', title: 'CA & Finance Manager',
        email: 'aditya.gupta.ca@gmail.com', phone: '+91 98901 23456',
        location: 'Mumbai, Maharashtra', linkedin: 'linkedin.com/in/adityagupta-ca',
        github: '', website: '',
        summary: 'CA with 8 years in financial reporting and taxation for listed companies and Big 4. Managed ₹2500Cr balance sheet. Expert in Ind AS/IFRS, GST, and direct tax. CFA Level 3 candidate.',
      },
      skills: {
        technical: ['Ind AS/IFRS', 'Financial Reporting', 'Consolidation', 'Audit', 'Direct Tax', 'GST', 'Transfer Pricing'],
        soft: ['Attention to Detail', 'Stakeholder Communication', 'Team Management'],
        tools: ['SAP FICO', 'Tally ERP', 'Advanced Excel', 'Power BI'],
        languages: [],
      },
      experience: [
        { company: 'Tata Consumer Products', role: 'Finance Manager', location: 'Mumbai', startDate: 'Apr 2020', endDate: '', current: true, description: 'Managed statutory and management reporting for ₹2500Cr revenue business unit.', bullets: ['Led Ind AS 116 implementation across 85 entities saving ₹12Cr in tax', 'Drove working capital optimization reducing cash conversion cycle by 18 days'] },
        { company: 'Deloitte India', role: 'Senior Audit Associate', location: 'Mumbai', startDate: 'Oct 2016', endDate: 'Mar 2020', current: false, description: 'Led statutory audits for BSE/NSE listed companies.', bullets: ['Identified ₹8Cr revenue leakage in manufacturing client'] },
      ],
      education: [
        { institution: 'ICAI', degree: 'Chartered Accountant', field: 'Finance', startYear: '2013', endYear: '2016', gpa: 'AIR 28', honors: '' },
        { institution: 'SRCC Delhi University', degree: 'B.Com (Hons)', field: 'Commerce', startYear: '2010', endYear: '2013', gpa: 'First Class', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 12, filename: 'finance_02_sunita_rao.pdf',
    name: 'Sunita Rao', title: 'Investment Banking Analyst',
    category: 'finance', level: 'Mid', ats: 95,
    resumeData: {
      title: 'Sunita Rao — Investment Banking Resume',
      template: 'modern', templateColor: '#10B981',
      targetRole: 'Investment Banking Associate',
      personal: {
        name: 'Sunita Rao', title: 'Investment Banking Analyst',
        email: 'sunita.rao.ib@gmail.com', phone: '+91 87901 23456',
        location: 'Mumbai, Maharashtra', linkedin: 'linkedin.com/in/sunitarao-ib',
        github: '', website: '',
        summary: 'Investment Banking professional with 5 years executing M&A, ECM, and DCM transactions worth $4B+. MBA from IIM Calcutta. CFA Charterholder. Deep expertise in financial modeling and valuation.',
      },
      skills: {
        technical: ['M&A Advisory', 'ECM/DCM', 'DCF Valuation', 'LBO Modeling', 'Merger Models', 'Pitchbooks'],
        soft: ['Client Management', 'Executive Presentation', 'Attention to Detail'],
        tools: ['Bloomberg', 'Capital IQ', 'FactSet', 'Advanced Excel', 'PowerPoint'],
        languages: [],
      },
      experience: [
        { company: 'Kotak Investment Banking', role: 'Associate – Investment Banking', location: 'Mumbai', startDate: 'Jul 2021', endDate: '', current: true, description: 'Executed $1.8B acquisition — largest India deal 2023.', bullets: ['Managed IPO process for 3 companies raising ₹4200Cr total', 'Built complex merger models for C-suite strategic decisions'] },
        { company: 'ICICI Securities', role: 'Analyst – Corporate Finance', location: 'Mumbai', startDate: 'Jun 2019', endDate: 'Jun 2021', current: false, description: 'Supported 8 QIP and rights issue transactions raising $800M+.', bullets: ['Performed valuations using DCF, EV/EBITDA, and precedent transaction analysis'] },
      ],
      education: [
        { institution: 'IIM Calcutta', degree: 'MBA', field: 'Finance', startYear: '2017', endYear: '2019', gpa: '3.9/4.0', honors: 'Gold Medal' },
        { institution: 'IIT Madras', degree: 'B.Tech', field: 'Computer Science', startYear: '2013', endYear: '2017', gpa: '9.2/10', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 13, filename: 'finance_03_amit_joshi.pdf',
    name: 'Amit Joshi', title: 'FP&A Manager',
    category: 'finance', level: 'Mid', ats: 94,
    resumeData: {
      title: 'Amit Joshi — FP&A Resume',
      template: 'modern', templateColor: '#10B981',
      targetRole: 'FP&A Manager',
      personal: {
        name: 'Amit Joshi', title: 'FP&A Manager',
        email: 'amit.joshi.fpa@outlook.com', phone: '+91 76890 12345',
        location: 'Pune, Maharashtra', linkedin: 'linkedin.com/in/amitjoshi-fpa',
        github: '', website: '',
        summary: 'FP&A professional with 7 years partnering with business leaders to drive profitable growth through data-driven insights. Expert in financial modeling and strategic planning for $200M+ revenue businesses.',
      },
      skills: {
        technical: ['Budgeting & Forecasting', 'Variance Analysis', 'Strategic Planning', 'Financial Modeling', 'KPI Design'],
        soft: ['Business Partnering', 'Executive Communication', 'Analytical Thinking'],
        tools: ['Anaplan', 'SAP BPC', 'Hyperion', 'Power BI', 'Tableau'],
        languages: [],
      },
      experience: [
        { company: 'Bajaj Auto', role: 'FP&A Manager', location: 'Pune', startDate: 'Mar 2020', endDate: '', current: true, description: 'Led annual budgeting for ₹35,000Cr revenue business with 500+ cost centers.', bullets: ['Built rolling forecast model improving accuracy from 78% to 94%', 'Identified ₹220Cr cost reduction opportunity through zero-based budgeting'] },
        { company: 'Mahindra & Mahindra', role: 'Senior Financial Analyst', location: 'Mumbai', startDate: 'Jun 2017', endDate: 'Feb 2020', current: false, description: 'Supported financial planning for Automotive division (₹20,000Cr revenue).', bullets: ['Automated MIS reporting saving 40 man-hours per month'] },
      ],
      education: [
        { institution: 'Symbiosis Institute of Business Management', degree: 'MBA', field: 'Finance', startYear: '2015', endYear: '2017', gpa: '', honors: '' },
        { institution: 'Fergusson College, Pune University', degree: 'B.Com (Hons)', field: 'Commerce', startYear: '2012', endYear: '2015', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 14, filename: 'finance_04_pooja_desai.pdf',
    name: 'Pooja Desai', title: 'Risk & Compliance Manager',
    category: 'finance', level: 'Senior', ats: 93,
    resumeData: {
      title: 'Pooja Desai — Risk & Compliance Resume',
      template: 'modern', templateColor: '#10B981',
      targetRole: 'Risk & Compliance Manager',
      personal: {
        name: 'Pooja Desai', title: 'Risk & Compliance Manager',
        email: 'pooja.desai.risk@gmail.com', phone: '+91 98654 32109',
        location: 'Mumbai, Maharashtra', linkedin: 'linkedin.com/in/poojadesai-risk',
        github: '', website: '',
        summary: 'Risk and Compliance professional with 8 years in banking. Expert in credit risk, operational risk, and regulatory compliance (RBI, SEBI, Basel III). Led compliance function for ₹5000Cr AUM NBFC. FRM and CA qualified.',
      },
      skills: {
        technical: ['Credit Risk', 'Operational Risk', 'Market Risk', 'RBI Regulations', 'SEBI Guidelines', 'Basel III', 'AML/KYC'],
        soft: ['Regulatory Liaison', 'Risk Communication', 'Report Writing'],
        tools: ['SAS Risk Management', "Moody's Analytics", 'Power BI', 'Excel'],
        languages: [],
      },
      experience: [
        { company: 'Piramal Finance', role: 'Risk & Compliance Manager', location: 'Mumbai', startDate: 'Jun 2019', endDate: '', current: true, description: 'Built enterprise risk framework for ₹5000Cr AUM wholesale lending business.', bullets: ['Reduced NPA ratio from 4.2% to 2.1% through improved credit underwriting models', 'Managed RBI inspection — zero major observations in 2022 and 2023 audits'] },
        { company: 'HDFC Bank', role: 'Credit Risk Analyst', location: 'Mumbai', startDate: 'Jul 2016', endDate: 'May 2019', current: false, description: 'Assessed credit proposals for SME and corporate borrowers (₹1Cr–₹200Cr).', bullets: ['Developed early warning system reducing credit defaults by 15%'] },
      ],
      education: [
        { institution: 'ICAI', degree: 'Chartered Accountant', field: 'Finance', startYear: '2013', endYear: '2016', gpa: '', honors: '' },
        { institution: 'Narsee Monjee College', degree: 'B.Com', field: 'Commerce', startYear: '2010', endYear: '2013', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 15, filename: 'finance_05_rohan_bhat.pdf',
    name: 'Rohan Bhat', title: 'Tax Consultant',
    category: 'finance', level: 'Mid', ats: 92,
    resumeData: {
      title: 'Rohan Bhat — Tax Consultant Resume',
      template: 'modern', templateColor: '#10B981',
      targetRole: 'Tax Manager',
      personal: {
        name: 'Rohan Bhat', title: 'Tax Consultant',
        email: 'rohan.bhat.tax@gmail.com', phone: '+91 88654 21098',
        location: 'Bangalore, Karnataka', linkedin: 'linkedin.com/in/rohanbhat-tax',
        github: '', website: '',
        summary: 'Tax professional with 6 years in direct and indirect taxation for MNCs, startups, and HNIs. Managed tax planning for ₹500Cr+ companies. Expert in transfer pricing, international tax, and GST. CA with LL.B.',
      },
      skills: {
        technical: ['Corporate Tax', 'Transfer Pricing', 'International Tax', 'Tax Litigation', 'GST', 'Customs', 'FEMA'],
        soft: ['Client Advisory', 'Legal Research', 'Negotiation'],
        tools: ['SAP', 'GSTN Portal', 'Income Tax Portal', 'Compliance Software'],
        languages: [],
      },
      experience: [
        { company: 'Ernst & Young (EY India)', role: 'Tax Manager', location: 'Bangalore', startDate: 'Sep 2021', endDate: '', current: true, description: 'Managed tax compliance for 20+ MNC clients across technology and manufacturing.', bullets: ['Led transfer pricing documentation for client with $500M intercompany transactions', 'Secured ₹35Cr tax refund through successful appeal before CIT(A)'] },
        { company: 'Grant Thornton India', role: 'Senior Tax Associate', location: 'Bangalore', startDate: 'Nov 2018', endDate: 'Aug 2021', current: false, description: 'Handled GST compliance and assessments for 30+ clients.', bullets: ['Represented clients before GST Appellate Authority — 80% success rate'] },
      ],
      education: [
        { institution: 'ICAI', degree: 'Chartered Accountant', field: 'Finance', startYear: '2015', endYear: '2018', gpa: '', honors: '' },
        { institution: 'Christ University Bangalore', degree: 'B.Com', field: 'Commerce', startYear: '2012', endYear: '2015', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 16, filename: 'education_01_lakshmi_subramaniam.pdf',
    name: 'Lakshmi Subramaniam', title: 'Senior School Teacher – Mathematics',
    category: 'education', level: 'Senior', ats: 95,
    resumeData: {
      title: 'Lakshmi Subramaniam — Teacher Resume',
      template: 'modern', templateColor: '#F59E0B',
      targetRole: 'Senior Mathematics Teacher',
      personal: {
        name: 'Lakshmi Subramaniam', title: 'Senior School Teacher – Mathematics',
        email: 'lakshmi.sub.teacher@gmail.com', phone: '+91 97543 21876',
        location: 'Chennai, Tamil Nadu', linkedin: 'linkedin.com/in/lakshmisubramaniam-edu',
        github: '', website: '',
        summary: 'Dedicated Mathematics educator with 12 years transforming students\' relationship with numbers. National Award for Teachers recipient. Innovative classroom techniques boosted board exam scores by 40%.',
      },
      skills: {
        technical: ['Curriculum Design', 'Differentiated Instruction', 'Inquiry-Based Learning', 'STEM Integration', 'Formative Assessment'],
        soft: ['Patience', 'Communication', 'Mentoring', 'Empathy'],
        tools: ['Google Classroom', 'Khan Academy', 'Desmos', 'GeoGebra', 'Smart Board'],
        languages: [],
      },
      experience: [
        { company: 'DAV Senior Secondary School', role: 'Senior Mathematics Teacher', location: 'Chennai', startDate: 'Jul 2015', endDate: '', current: true, description: 'Taught Mathematics to 400+ students annually across Class 9–12 (CBSE).', bullets: ['Improved Class 12 board exam pass rate from 78% to 97% over 3 years', 'Developed workbooks adopted by 8 schools in the DAV network'] },
        { company: 'Kendriya Vidyalaya', role: 'Mathematics Teacher', location: 'Chennai', startDate: 'Jun 2012', endDate: 'Jun 2015', current: false, description: 'Taught Mathematics to Classes 6–10 with consistent above-average results.', bullets: ['Designed remedial program reducing failure rate from 15% to 3%'] },
      ],
      education: [
        { institution: 'University of Madras', degree: 'M.Sc', field: 'Mathematics', startYear: '2010', endYear: '2012', gpa: 'First Class with Distinction', honors: '' },
        { institution: 'Stella Maris College Chennai', degree: 'B.Sc', field: 'Mathematics', startYear: '2007', endYear: '2010', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 17, filename: 'education_02_dr_suresh_pillai.pdf',
    name: 'Dr. Suresh Pillai', title: 'Associate Professor – CS',
    category: 'education', level: 'Lead', ats: 94,
    resumeData: {
      title: 'Dr. Suresh Pillai — Professor Resume',
      template: 'modern', templateColor: '#F59E0B',
      targetRole: 'Associate Professor',
      personal: {
        name: 'Dr. Suresh Pillai', title: 'Associate Professor – Computer Science',
        email: 'drsuresh.pillai@university.edu', phone: '+91 94321 09876',
        location: 'Kochi, Kerala', linkedin: 'linkedin.com/in/drsureshpillai-cs',
        github: '', website: '',
        summary: 'Associate Professor with 14 years in academia. PhD in Distributed Systems from IIT Madras. Published 28 research papers (Scopus indexed). Secured ₹1.2Cr in research grants. H-index 12.',
      },
      skills: {
        technical: ['Cloud Computing', 'Distributed Systems', 'Algorithms', 'Machine Learning', 'Operating Systems', 'Research Methodology'],
        soft: ['Academic Writing', 'Research Supervision', 'Grant Writing', 'Peer Review'],
        tools: ['MATLAB', 'Python', 'R', 'LaTeX', 'SPSS'],
        languages: [],
      },
      experience: [
        { company: 'College of Engineering Trivandrum (CET)', role: 'Associate Professor – Computer Science', location: 'Kochi', startDate: 'Jan 2018', endDate: '', current: true, description: 'Teaching UG and PG courses in Cloud Computing, Distributed Systems, and ML.', bullets: ['Supervised 12 M.Tech theses and 2 PhD scholars', 'Published 18 papers in Q1/Q2 Scopus journals since 2018', 'Secured ₹80L DST research grant on Edge Computing for Smart Cities'] },
        { company: 'NIT Calicut', role: 'Assistant Professor', location: 'Calicut', startDate: 'Jul 2012', endDate: 'Dec 2017', current: false, description: 'Taught Data Structures, OS, and Computer Networks to 200+ students per semester.', bullets: ['Published 10 research papers; H-index of 8'] },
      ],
      education: [
        { institution: 'IIT Madras', degree: 'PhD', field: 'Distributed Systems', startYear: '2009', endYear: '2012', gpa: '', honors: '' },
        { institution: 'NIT Calicut', degree: 'M.Tech', field: 'Computer Science', startYear: '2005', endYear: '2007', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 18, filename: 'education_03_nandini_chopra.pdf',
    name: 'Nandini Chopra', title: 'Primary School Teacher',
    category: 'education', level: 'Mid', ats: 93,
    resumeData: {
      title: 'Nandini Chopra — Primary Teacher Resume',
      template: 'modern', templateColor: '#F59E0B',
      targetRole: 'Senior Primary Teacher',
      personal: {
        name: 'Nandini Chopra', title: 'Primary School Teacher & Curriculum Designer',
        email: 'nandini.chopra.edu@gmail.com', phone: '+91 83456 78901',
        location: 'New Delhi', linkedin: 'linkedin.com/in/nandinichopra-teacher',
        github: '', website: '',
        summary: 'Passionate primary educator with 9 years creating joyful, inquiry-based learning environments. Montessori certified. Designed district-wide curriculum adopted by 40 schools in Delhi.',
      },
      skills: {
        technical: ['Child-Centered Learning', 'Montessori Method', 'Project-Based Learning', 'Curriculum Design', 'IEP Development', 'Special Education'],
        soft: ['Empathy', 'Creativity', 'Parent Communication', 'Inclusivity'],
        tools: ['Google Classroom', 'Seesaw', 'Padlet', 'Canva for Education'],
        languages: [],
      },
      experience: [
        { company: 'The Shri Ram School', role: 'Senior Primary Teacher & Curriculum Coordinator', location: 'New Delhi', startDate: 'Apr 2018', endDate: '', current: true, description: 'Teaching Classes 1–5 English and EVS to 120+ students.', bullets: ['Designed integrated thematic curriculum adopted across 4 school branches', 'Established inclusive practices supporting 12 students with learning differences'] },
        { company: 'Sanskriti School', role: 'Primary Teacher', location: 'New Delhi', startDate: 'Jul 2015', endDate: 'Mar 2018', current: false, description: 'Implemented Montessori principles in mixed-age Class 1–3 classroom.', bullets: ['Parent satisfaction scores consistently above 95%'] },
      ],
      education: [
        { institution: 'IGNOU', degree: 'M.Ed', field: 'Early Childhood Education', startYear: '2015', endYear: '2017', gpa: '', honors: '' },
        { institution: 'Miranda House, Delhi University', degree: 'B.A.', field: 'English Literature', startYear: '2011', endYear: '2014', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 19, filename: 'education_04_ravi_shankar.pdf',
    name: 'Ravi Shankar', title: 'School Principal',
    category: 'education', level: 'Lead', ats: 92,
    resumeData: {
      title: 'Ravi Shankar — School Principal Resume',
      template: 'modern', templateColor: '#F59E0B',
      targetRole: 'School Principal',
      personal: {
        name: 'Ravi Shankar', title: 'School Principal & Education Administrator',
        email: 'ravi.shankar.principal@gmail.com', phone: '+91 99432 10876',
        location: 'Hyderabad, Telangana', linkedin: 'linkedin.com/in/ravishankar-principal',
        github: '', website: '',
        summary: 'Experienced school administrator with 20 years, including 8 years as Principal. Transformed a struggling school from C-grade to A+ CBSE accreditation. Expert in academic leadership and community engagement.',
      },
      skills: {
        technical: ['School Management', 'Academic Planning', 'Staff Development', 'Budget Management', 'Quality Assurance', 'CBSE Compliance'],
        soft: ['Visionary Leadership', 'Stakeholder Engagement', 'Change Management'],
        tools: ['School ERP Systems', 'ISO 9001', 'CBSE Portal'],
        languages: [],
      },
      experience: [
        { company: 'Glendale Academy CBSE School', role: 'Principal', location: 'Hyderabad', startDate: 'Apr 2016', endDate: '', current: true, description: 'Led transformation from C-grade to A+ CBSE school in 3 years (1200 students).', bullets: ['Increased student enrolment from 800 to 1800 through academic excellence', 'Reduced teacher attrition from 30% to 8% through structured mentoring'] },
        { company: 'Meridian School', role: 'Vice Principal', location: 'Hyderabad', startDate: 'Jun 2011', endDate: 'Mar 2016', current: false, description: 'Supervised academic operations for 2500+ students and 120 teaching staff.', bullets: ['Implemented SMART classroom technology across all 80 classrooms'] },
      ],
      education: [
        { institution: 'IGNOU', degree: 'MBA', field: 'Education Management', startYear: '2009', endYear: '2011', gpa: '', honors: '' },
        { institution: 'Osmania University', degree: 'M.Ed', field: 'Education', startYear: '2002', endYear: '2004', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 20, filename: 'education_05_aparna_menon.pdf',
    name: 'Aparna Menon', title: 'Corporate Trainer & L&D Specialist',
    category: 'education', level: 'Senior', ats: 91,
    resumeData: {
      title: 'Aparna Menon — L&D Specialist Resume',
      template: 'modern', templateColor: '#F59E0B',
      targetRole: 'L&D Manager',
      personal: {
        name: 'Aparna Menon', title: 'Corporate Trainer & L&D Specialist',
        email: 'aparna.menon.trainer@gmail.com', phone: '+91 91234 56789',
        location: 'Kochi, Kerala', linkedin: 'linkedin.com/in/aparname-trainer',
        github: '', website: '',
        summary: 'Corporate Training professional with 10 years designing impactful L&D programs for Fortune 500 companies. Trained 15,000+ professionals. ATD Master Trainer certified. Specialist in leadership development.',
      },
      skills: {
        technical: ['Instructional Design', 'Facilitation', 'Train the Trainer', 'E-Learning Design', 'Kirkpatrick Model', 'ROI Analysis'],
        soft: ['Public Speaking', 'Empathy', 'Storytelling', 'Coaching'],
        tools: ['Articulate 360', 'Adobe Captivate', 'Moodle LMS', 'Kahoot', 'Mentimeter'],
        languages: [],
      },
      experience: [
        { company: 'Wipro', role: 'Senior L&D Manager', location: 'Kochi / Pan India', startDate: 'Feb 2019', endDate: '', current: true, description: 'Designed leadership program for 500 mid-managers across 12 locations.', bullets: ['Built e-learning library of 120+ modules used by 45,000 employees globally', 'Saved ₹2.5Cr annually by converting instructor-led training to blended learning'] },
        { company: 'Infosys BPM', role: 'Corporate Trainer', location: 'Bangalore', startDate: 'Jul 2014', endDate: 'Jan 2019', current: false, description: 'Trained 8,000+ BPO professionals in communication and customer service.', bullets: ['Designed onboarding program reducing new joiner ramp-up time by 30%'] },
      ],
      education: [
        { institution: 'Calicut University', degree: 'M.A.', field: 'English & Communication', startYear: '2012', endYear: '2014', gpa: '', honors: '' },
        { institution: "St. Teresa's College Ernakulam", degree: 'B.A.', field: 'English Literature', startYear: '2009', endYear: '2012', gpa: '', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
  {
    id: 21, filename: 'freshers_01_rohan_verma.pdf',
    name: 'Rohan Verma', title: 'Fresher – Computer Science Engineer',
    category: 'freshers', level: 'Fresher', ats: 88,
    resumeData: {
      title: 'Rohan Verma — CS Fresher Resume',
      template: 'modern', templateColor: '#06B6D4',
      targetRole: 'Software Developer',
      personal: {
        name: 'Rohan Verma', title: 'Computer Science Engineer',
        email: 'rohan.verma.cs22@gmail.com', phone: '+91 89012 34567',
        location: 'Jaipur, Rajasthan', linkedin: 'linkedin.com/in/rohanverma-cs',
        github: 'github.com/rohanverma-codes', website: '',
        summary: 'Passionate CS graduate from NIT Jaipur with strong fundamentals in DSA and full-stack development. Built 4 personal projects with 500+ GitHub stars. SIH 2023 Grand Finalist. Seeking Software Developer role.',
      },
      skills: {
        technical: ['C++', 'Python', 'JavaScript', 'Java', 'React', 'Node.js', 'Express'],
        soft: ['Problem Solving', 'Quick Learning', 'Teamwork', 'Communication'],
        tools: ['Git', 'VS Code', 'Postman', 'Linux', 'MySQL', 'MongoDB', 'Firebase'],
        languages: [],
      },
      experience: [
        { company: 'Juspay Technologies', role: 'Software Development Intern', location: 'Bangalore (Remote)', startDate: 'May 2023', endDate: 'Jul 2023', current: false, description: 'Built REST APIs for payment gateway SDK reducing integration time by 25%.', bullets: ['Implemented Redis caching cutting API response time by 40%', 'Fixed 15 bugs in production React dashboard and improved test coverage by 20%'] },
        { company: 'EdTech Startup', role: 'Web Development Intern', location: 'Remote', startDate: 'Dec 2022', endDate: 'Feb 2023', current: false, description: 'Developed student progress tracking dashboard using React and Chart.js.', bullets: ['Integrated Razorpay payment gateway for course subscriptions'] },
      ],
      education: [{ institution: 'NIT Jaipur', degree: 'B.Tech', field: 'Computer Science', startYear: '2020', endYear: '2024', gpa: '8.6/10', honors: '' }],
      projects: [
        { name: 'CodeCollab', description: 'Real-time collaborative code editor — 300+ GitHub stars', technologies: ['React', 'Node.js', 'Socket.io', 'Monaco Editor'], url: '', github: 'github.com/rohanverma-codes/codecollab' },
        { name: 'StudyBuddy AI', description: 'AI-powered study assistant — built in 48hr hackathon, won 2nd prize', technologies: ['Python', 'OpenAI API', 'Flask'], url: '', github: '' },
      ],
      certifications: [],
    },
  },
  {
    id: 22, filename: 'freshers_02_ishaan_kapoor.pdf',
    name: 'Ishaan Kapoor', title: 'Fresher – Data Science',
    category: 'freshers', level: 'Fresher', ats: 87,
    resumeData: {
      title: 'Ishaan Kapoor — Data Science Fresher Resume',
      template: 'modern', templateColor: '#06B6D4',
      targetRole: 'Data Scientist / Data Analyst',
      personal: {
        name: 'Ishaan Kapoor', title: 'Data Science & Analytics',
        email: 'ishaan.kapoor.ds@gmail.com', phone: '+91 78901 23456',
        location: 'Chandigarh, Punjab', linkedin: 'linkedin.com/in/ishaankapoor-ds',
        github: 'github.com/ishaankapoor-ml', website: '',
        summary: 'Data Science graduate with ML and statistical analysis experience. Built predictive models with 92%+ accuracy. Kaggle Expert (top 8%). Looking for Data Analyst / Data Scientist role.',
      },
      skills: {
        technical: ['Machine Learning', 'Statistical Analysis', 'A/B Testing', 'Python', 'R', 'SQL'],
        soft: ['Analytical Thinking', 'Data Storytelling', 'Attention to Detail'],
        tools: ['Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'Tableau', 'Power BI', 'BigQuery'],
        languages: [],
      },
      experience: [
        { company: 'Groww', role: 'Data Science Intern', location: 'Bangalore (Hybrid)', startDate: 'Jun 2023', endDate: 'Aug 2023', current: false, description: 'Built churn prediction model with 89% accuracy identifying at-risk investors.', bullets: ['Performed cohort analysis on 500K users revealing key retention drivers', 'Created Tableau dashboard for retention KPIs used by Product and Marketing'] },
        { company: 'IIT Ropar – Data Lab', role: 'Research Intern', location: 'Ropar', startDate: 'Dec 2022', endDate: 'Mar 2023', current: false, description: 'Analyzed agricultural price data for 15 crops across 20 years.', bullets: ['Achieved RMSE of 12.3% on price prediction model — paper under review'] },
      ],
      education: [{ institution: 'BITS Pilani Goa Campus', degree: 'B.Sc', field: 'Data Science & AI', startYear: '2020', endYear: '2024', gpa: '8.4/10', honors: '' }],
      projects: [
        { name: 'CreditRisk ML', description: 'Loan default prediction — 92.3% AUC, deployed as web app', technologies: ['Python', 'XGBoost', 'SHAP', 'Streamlit'], url: '', github: 'github.com/ishaankapoor-ml/creditrisk' },
        { name: 'IPL Win Predictor', description: 'Real-time win probability — 500+ daily users during IPL 2023', technologies: ['Python', 'Random Forest', 'Streamlit'], url: '', github: '' },
      ],
      certifications: [],
    },
  },
  {
    id: 23, filename: 'freshers_03_tanvi_shah.pdf',
    name: 'Tanvi Shah', title: 'Fresher – MBA Marketing',
    category: 'freshers', level: 'Fresher', ats: 86,
    resumeData: {
      title: 'Tanvi Shah — MBA Marketing Fresher Resume',
      template: 'modern', templateColor: '#06B6D4',
      targetRole: 'Marketing Executive / Brand Manager',
      personal: {
        name: 'Tanvi Shah', title: 'MBA Marketing Graduate',
        email: 'tanvi.shah.mba@gmail.com', phone: '+91 96789 01234',
        location: 'Ahmedabad, Gujarat', linkedin: 'linkedin.com/in/tanvishah-marketing',
        github: '', website: '',
        summary: 'MBA Marketing graduate from NMIMS. Strong in digital marketing, brand management, and consumer research. Completed 3 internships. Grew D2C brand social following by 300%.',
      },
      skills: {
        technical: ['Digital Marketing', 'Brand Management', 'Consumer Research', 'Campaign Planning', 'Social Media Marketing'],
        soft: ['Creativity', 'Communication', 'Market Insight', 'Storytelling'],
        tools: ['Google Analytics', 'Meta Ads Manager', 'Canva', 'HubSpot', 'Mailchimp'],
        languages: [],
      },
      experience: [
        { company: 'Marico Limited', role: 'Marketing Intern', location: 'Mumbai', startDate: 'Apr 2023', endDate: 'Jun 2023', current: false, description: 'Assisted in brand planning for Saffola and ran social media campaigns.', bullets: ['Campaign achieved 2.3M impressions', 'Conducted 80+ consumer interviews for product concept testing'] },
        { company: 'The Whole Truth Foods', role: 'Digital Marketing Intern', location: 'Remote', startDate: 'Oct 2022', endDate: 'Dec 2022', current: false, description: 'Grew Instagram following from 45K to 58K through content strategy revamp.', bullets: ['Managed ₹5L Meta ads budget achieving 2.8x ROAS for festive campaign'] },
      ],
      education: [
        { institution: 'NMIMS Mumbai', degree: 'MBA', field: 'Marketing', startYear: '2022', endYear: '2024', gpa: '3.7/4.0', honors: '' },
        { institution: 'HL College of Commerce', degree: 'B.Com', field: 'Commerce', startYear: '2019', endYear: '2022', gpa: 'First Class', honors: '' },
      ],
      projects: [{ name: 'D2C Growth Strategy', description: 'Grew skincare D2C brand revenue by 40% in 3 months', technologies: ['Google Ads', 'Meta Ads', 'Email Marketing'], url: '', github: '' }],
      certifications: [],
    },
  },
  {
    id: 24, filename: 'freshers_04_ayesha_khan.pdf',
    name: 'Ayesha Khan', title: 'Fresher – Civil Engineer',
    category: 'freshers', level: 'Fresher', ats: 85,
    resumeData: {
      title: 'Ayesha Khan — Civil Engineer Fresher Resume',
      template: 'modern', templateColor: '#06B6D4',
      targetRole: 'Junior Civil Engineer',
      personal: {
        name: 'Ayesha Khan', title: 'Civil Engineer',
        email: 'ayesha.khan.civil@gmail.com', phone: '+91 85678 90123',
        location: 'Lucknow, Uttar Pradesh', linkedin: 'linkedin.com/in/ayeshakhan-civil',
        github: '', website: '',
        summary: 'Civil Engineering graduate with strong foundation in structural design and AutoCAD. Completed 6-month internship with L&T Construction on metro rail project. GATE 2024 qualified. Detail-oriented engineer.',
      },
      skills: {
        technical: ['Structural Analysis', 'RCC Design', 'AutoCAD', 'STAAD.Pro', 'Revit', 'Project Planning', 'Cost Estimation'],
        soft: ['Detail-Oriented', 'Site Coordination', 'Technical Report Writing'],
        tools: ['AutoCAD', 'STAAD.Pro', 'ETABS', 'Revit', 'MS Project'],
        languages: [],
      },
      experience: [
        { company: 'Larsen & Toubro Construction', role: 'Site Engineering Intern', location: 'Lucknow Metro Project', startDate: 'Jan 2024', endDate: 'Jun 2024', current: false, description: 'Assisted resident engineer in daily site supervision for 2km elevated viaduct section.', bullets: ['Prepared daily progress reports and quality control checklists for 500+ inspection points', 'Used AutoCAD to draft as-built drawings for 3 station structures'] },
        { company: 'State PWD, UP Government', role: 'Survey Intern', location: 'Lucknow', startDate: 'Jun 2023', endDate: 'Jul 2023', current: false, description: 'Conducted topographic survey for 15km rural road project.', bullets: ['Prepared cross-section drawings using Total Station data'] },
      ],
      education: [{ institution: 'KNIT Sultanpur (UPTU)', degree: 'B.Tech', field: 'Civil Engineering', startYear: '2020', endYear: '2024', gpa: '8.1/10', honors: '' }],
      projects: [{ name: 'Seismic Analysis of G+10 RCC Frame', description: 'B.Tech thesis — comparative study in Seismic Zone IV', technologies: ['STAAD.Pro', 'IS 1893'], url: '', github: '' }],
      certifications: [],
    },
  },
  {
    id: 25, filename: 'freshers_05_harsh_agarwal.pdf',
    name: 'Harsh Agarwal', title: 'Fresher – CA Aspirant',
    category: 'freshers', level: 'Fresher', ats: 84,
    resumeData: {
      title: 'Harsh Agarwal — CA Fresher Resume',
      template: 'modern', templateColor: '#06B6D4',
      targetRole: 'Article Assistant / Junior Accountant',
      personal: {
        name: 'Harsh Agarwal', title: 'Commerce Graduate & CA Aspirant',
        email: 'harsh.agarwal.ca@gmail.com', phone: '+91 73456 78901',
        location: 'Jaipur, Rajasthan', linkedin: 'linkedin.com/in/harshagarwal-ca',
        github: '', website: '',
        summary: 'B.Com graduate with CA Inter cleared (Both Groups) and 1 year articleship. Strong in accounting, audit, and taxation. Cleared CA Foundation in first attempt. Seeking articleship or junior accounting role.',
      },
      skills: {
        technical: ['Financial Accounting', 'Cost Accounting', 'Tally ERP', 'Internal Audit', 'Statutory Audit', 'GST Filing', 'TDS Compliance'],
        soft: ['Accuracy', 'Compliance Mindset', 'Analytical Thinking'],
        tools: ['Tally Prime', 'Advanced Excel', 'Income Tax Portal', 'GSTN Portal', 'SAP Basics'],
        languages: [],
      },
      experience: [
        { company: 'M/s Agarwal & Associates, CAs', role: 'Article Assistant', location: 'Jaipur', startDate: 'Jan 2023', endDate: '', current: true, description: 'Assisted in statutory audits of 12 SME companies across manufacturing and trading.', bullets: ['Prepared GST returns (GSTR-1, 3B, 9, 9C) for 25+ clients monthly', 'Filed income tax returns (ITR-3, ITR-6) for 40+ individuals and companies'] },
        { company: 'Motilal Oswal Financial Services', role: 'Accounting Intern', location: 'Jaipur', startDate: 'May 2022', endDate: 'Jun 2022', current: false, description: 'Reconciled client trading accounts and ledgers.', bullets: ['Assisted in preparation of monthly MIS reports for branch'] },
      ],
      education: [
        { institution: 'ICAI', degree: 'CA Inter', field: 'Both Groups Cleared', startYear: '2022', endYear: '2023', gpa: '56%', honors: '' },
        { institution: 'University of Rajasthan', degree: 'B.Com (Hons)', field: 'Commerce', startYear: '2019', endYear: '2022', gpa: 'First Division – 74%', honors: '' },
      ],
      projects: [],
      certifications: [],
    },
  },
];
